openapi: 3.0.0
info:
  title: Jobster API
  contact: {}
  version: '1.0'
servers:
  - url: http://localhost:3000/api/v1
    variables: {}
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      operationId: RegisterUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/RegisterUserRequest'
                - example:
                    name: john
                    email: john@gmail.com
                    password: secret
            example:
              name: john
              email: john@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      operationId: LoginUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/LoginUserRequest'
                - example:
                    email: john@gmail.com
                    password: secret
            example:
              email: john@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/updateuser:
    patch:
      tags:
        - Auth
      summary: Update User
      description: ''
      operationId: UpdateUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/UpdateUserRequest'
                - example:
                    email: john@gmail.com
                    name: john
                    lastName: jack
                    location: london
            example:
              email: john@gmail.com
              name: john
              lastName: jack
              location: london
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /jobs:
    post:
      tags:
        - Jobs
      summary: Create Job
      operationId: CreateJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/CreateJobRequest'
                - example:
                    company: google
                    position: fullstack developer
                    jobType: full-time
                    jobLocation: london
            example:
              company: google
              position: fullstack developer
              jobType: full-time
              jobLocation: london
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
    get:
      tags:
        - Jobs
      summary: Get All Jobs
      operationId: GetAllJobs
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID
    get:
      tags:
        - Jobs
      summary: Get Job
      operationId: GetJob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
    patch:
      tags:
        - Jobs
      summary: Update Job
      operationId: UpdateJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/UpdateJobRequest'
                - example:
                    company: google
                    position: senior fullstack developer
                    jobType: full-time
            example:
              company: google
              position: senior fullstack developer
              jobType: full-time
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
    delete:
      tags:
        - Jobs
      summary: Delete Job
      operationId: DeleteJob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /jobs/stats:
    get:
      tags:
        - Jobs
      summary: Get Stats
      description: ''
      operationId: GetStats
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
        - bearer: []
components:
  schemas:
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: john
        email: john@gmail.com
        password: secret
    LoginUserRequest:
      title: LoginUserRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: john@gmail.com
        password: secret
    CreateJobRequest:
      title: CreateJobRequest
      required:
        - company
        - position
        - jobType
        - jobLocation
      type: object
      properties:
        company:
          type: string
        position:
          type: string
        jobType:
          type: string
        jobLocation:
          type: string
      example:
        company: google
        position: fullstack developer
        jobType: full-time
        jobLocation: london
    UpdateJobRequest:
      title: UpdateJobRequest
      required:
        - company
        - position
        - jobType
      type: object
      properties:
        company:
          type: string
        position:
          type: string
        jobType:
          type: string
      example:
        company: google
        position: senior fullstack developer
        jobType: full-time
    UpdateUserRequest:
      title: UpdateUserRequest
      required:
        - email
        - name
        - lastName
        - location
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        lastName:
          type: string
        location:
          type: string
      description: ''
      example:
        email: john@gmail.com
        name: john
        lastName: jack
        location: london
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Auth
    description: ''
  - name: Jobs
    description: ''
